AWSTemplateFormatVersion: "2010-09-09"
Transform: "AWS::Serverless-2016-10-31"
Resources:
  EmailFunction:
    Type: "AWS::Serverless::Function"
    Properties:
      Handler: email_function.lambda_handler
      Runtime: python3.11
      CodeUri: .
      MemorySize: 128
      Timeout: 10
